### ISSUE TITLE
LDAP connection pool doesn't increment numFailedConnectionAttempts stats on failed LDAP connect

### ISSUE THREAD

**Issue by vdzhuvinov** [UnboundID/ldapsdk#12]
Hello,

A while ago we started plotting the LDAP connection pool stats to monitor our LDAP backend. We noticed that `numFailedConnectionAttempts` stays at zero even though we'd encountered clear connection failures (LDAP server down). It looks like for some reason only `numFailedCheckouts` gets incremented. I'm not sure if that's supposed behaviour.

**Comment by dirmgr** [comment]
Thanks for pointing this out. I've committed a change that should fix this.

**Comment by vdzhuvinov** [comment]
Thank you for looking into this! I truly love this library and its utility is fantastic.

**Comment by vdzhuvinov** [comment]
I'd like to confirm this as fixed in 3.1.1.
