### ISSUE TITLE
Let LDAPConnection implement java.io.Closeable

### ISSUE THREAD

**Issue by vdzhuvinov** [UnboundID/ldapsdk#15]
This will enable try-with-resources statements in Java 7 and later. Closeable is available since Java 5.

**Comment by dirmgr** [comment]
This has been committed. A unit test is now in place to ensure that any public class that includes a "public void close()" method whose only checked exception is an optional IOException implements the java.io.Closeable interface.

**Comment by vdzhuvinov** [comment]
Thanks, this is much appreciated! Coding with the LDAP SDK becomes even more enjoyable now :)
