### ISSUE TITLE
Create a `Schema` from an `InputStream`

### ISSUE THREAD

**Issue by snicoll** [UnboundID/ldapsdk#23]
We've added LDAP integration in Spring Boot and @mouellet submitted a PR to offer validation for embedded LDAP (see https://github.com/spring-projects/spring-boot/pull/8195).

The problem is that the schema can be on disk or on the classpath (usually it would be in the classpath). There isn't a public method to create a `Schema` from a `java.io.InputStream`. It would be nice if that option was available. 

Thoughts? Thanks!

**Comment by dirmgr** [comment]
I just committed a change to add a Schema.getSchema method that can read LDIF-formatted schema information from a provided input stream. It's available now if you want to build the LDAP SDK for yourself, and it will be in the next LDAP SDK release, which will probably be within the next couple of weeks.

**Comment by snicoll** [comment]
@dirmgr looks good thanks! Shouldn't this issue closed by now?

**Comment by snicoll** [comment]
FYI, I've integrated that change that works fine. We'll include it in Spring Boot 1.5.2 to be released soon. Thank for the quick assistance!

**Comment by dirmgr** [comment]
If you're satisfied with the change, then we can close it.
