### ISSUE TITLE
size limit over STARTTLS

### ISSUE THREAD

**Issue by phi1ipp** [UnboundID/ldapsdk#4]
Hey guys,

Thank you for the nice library first of all.

I noticed a strange behavior while doing searces over plain and starttls as a cn=manager.... Server side sizelimit seems not effective on a plain connection but kicks in when on STARTTLS. So I hit size limit exception when I jump to secure connection. 

Is it an known/expected thing?

Thank you,
Philipp

**Comment by dirmgr** [comment]
This is not something that anyone else has reported, nor is it behavior that we have seen for ourselves.  The LDAP SDK unit test framework includes tests that verify that the search size limit is honored as expected, and those tests pass over both secure and non-secure connections.

The search request that the LDAP SDK sends to a server should not vary in any way based on whether StartTLS has previously been used on the connection.  If you're seeing that a directory server is processing the request differently on an unencrypted connection versus one that has been secured with StartTLS, then that sounds like an issue with the server.

Are you explicitly setting a size limit in the search request?  If you don't specify a size limit, then the LDAP SDK will use a default size limit of zero, indicating that the client does not want any limit to be used.  However, the server may override the client-specified size limit to impose a lower limit.  It is possible that the server may impose a different limit under different circumstances (e.g., it is common for directory servers to be able to impose different maximum size limit values for different users), so it is conceivable that something in the server configuration causes it to impose a different limit for connections secured with StartTLS than for unsecured connections.  It is also possible that there is some other difference in the connection state that could account for the difference in the observed behavior (e.g., the requests are being issued as different users over secure and insecure connections).

**Comment by phi1ipp** [comment]
Thank you for the prompt reply. I'm not setting a limit while requesting so I believe it's something on a the server end then. It's the same, same request for both types of connections. 

I'll check the code against a different instance of LDAP and let you know if the problem still exists.
