### ISSUE TITLE
Could not find COMPLETELY_THREADSAFE in enum object ThreadSafetyLevel

### ISSUE THREAD

**Issue by irundaia** [UnboundID/ldapsdk#6]
Hi,

I'm working in a business where we use the unboundid ldapsdk to authenticate users. Our project management has decided to increase the "quality" of our code by forcing warnings to be treated as errors. 
Now, the problem is, that when using the ldapsdk library, the scala compiler issues a warning stating that it cannot find COMPLETELY_THREADSAFE (which now breaks our build). See also:

> While parsing annotations in path\to\unboundid-ldapsdk-3.0.0.jar (com/unboundid/util/ThreadSafetyLevel.class), could not find COMPLETELY_THREADSAFE in enum object ThreadSafetyLevel.
This is likely due to an implementation restriction: an annotation argument cannot refer to a member of the annotated class (SI-7014).

Do you have any idea on how I could solve this?

**Comment by dirmgr** [comment]
Although I had never seen this warning before, I believe that I have been able to identify and correct the problem.

Virtually all public classes within the LDAP SDK include a ThreadSafety annotation that is intended to provide developers with information about whether or not instances of that class are expected to be safe for concurrent use across multiple threads.  The ThreadSafety annotation should include a ThreadSafetyLevel value, where ThreadSafetyLevel is an enum with values like COMPLETELY_THREADSAFE, MOSTLY_THREADSAFE, MOSTLY_NOT_THREADSAFE, and NOT_THREADSAFE (and in cases where the value is MOSTLY_THREADSAFE or MOSTLY_NOT_THREADSAFE, the Javadoc should provide more details about which uses are/are not threadsafe).

I believe that the problem you've encountered is that the ThreadSafetyLevel enum was marked with a ThreadSafety annotation, and that annotation included a ThreadSafetyLevel value.  The compiler doesn't like that the enum is marked with an annotation that references a value of that enum.

I have just committed an update to the LDAP SDK that removed the ThreadSafety annotation from the ThreadSafetyLevel enum, and I believe that this should fix the problem.

**Comment by irundaia** [comment]
That would be great thank you!

**Comment by dirmgr** [comment]
The commit is in the repository now, so you can check out and build the LDAP SDK for yourself to see if that fixes the problem.  The code in the repository is always kept in a production-ready state, so you shouldn't have any concerns about using a jar that you built for yourself.  As long as you don't alter the LDAP SDK itself when you build it, we will provide the same level of support for any version that you build yourself as we do for official builds that we release.

**Comment by irundaia** [comment]
I've tested the fix, and it works now. Do you have any idea when you might publish the next release? I'm asking because we are moving toward a maven build which automatically resolves external dependencies (hopefully including the ldapsdk). 

For now, we'll keep using the manually built jar. Thank you for the quick support!

**Comment by dirmgr** [comment]
I don't have a specific date right now, but my guess is that the next official release will be in mid to late December.  It will almost certainly be before the end of the year.

**Comment by irundaia** [comment]
Great, thank you for your help

**Comment by briandignan** [comment]
I've been dealing with this warning as well. Looking forward to the next release!

**Comment by irundaia** [comment]
With the new release, I assume that this issue can now be closed. Thanks for the help.
